DROP DATABASE IF EXISTS `myweb`;

CREATE DATABASE `myweb` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `myweb`;
CREATE TABLE IF NOT EXISTS users(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(100) NOT NULL,
   phone VARCHAR(15) NOT NULL UNIQUE,
   email VARCHAR(100) NOT NULL UNIQUE,
   pass VARCHAR(100) NOT NULL,
   dateDK DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
   male VARCHAR(15) NOT NULL,
   bDate Date,
   imgSrc VARCHAR(100)
);